"""Canonical Cairn data model.

These are the types that flow across layer boundaries. They are the contract
between ingestion, indexing, retrieval, and the MCP server. Treat them as the
schema; never substitute ad-hoc dicts.

Mirrors ARCHITECTURE.md §4. Changes here are breaking and require an ADR.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationInfo, field_validator

EntityKind = Literal["term", "code", "proper", "defined"]
XRefKind = Literal["link", "textual", "entity"]


class _Frozen(BaseModel):
    """Common config for immutable, strict models."""

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
        str_strip_whitespace=False,
        validate_assignment=True,
    )


class Span(_Frozen):
    """A half-open byte range `[start, end)` in the source document."""

    start: int = Field(ge=0)
    end: int = Field(ge=0)

    @field_validator("end")
    @classmethod
    def _end_after_start(cls, end: int, info: ValidationInfo) -> int:
        start = info.data.get("start")
        if isinstance(start, int) and end < start:
            msg = f"Span.end ({end}) must be >= Span.start ({start})"
            raise ValueError(msg)
        return end

    def __len__(self) -> int:
        return self.end - self.start


class SectionNode(_Frozen):
    """A node in the document's structural tree.

    `id` is hierarchical, slug-based, and stable across re-indexing of the
    same document. Example: ``hooks/use-effect/cleanup``.

    `raw_text` is the body that belongs **directly** to this section, excluding
    any descendant sections' bodies. To read continuous text including
    descendants, use the `span` and read from the source — or use the
    `read_range` retrieval tool.
    """

    id: str = Field(min_length=1)
    title: str
    level: int = Field(ge=1, le=6)
    parent: str | None
    children: tuple[str, ...] = ()
    span: Span
    path: tuple[str, ...]
    raw_text: str

    @field_validator("id")
    @classmethod
    def _id_well_formed(cls, value: str) -> str:
        if value.startswith("/") or value.endswith("/"):
            msg = f"section id must not start or end with '/': {value!r}"
            raise ValueError(msg)
        if "//" in value:
            msg = f"section id must not contain '//': {value!r}"
            raise ValueError(msg)
        return value


class SummarySet(_Frozen):
    """Multi-granularity summaries for one section.

    Generated by a `Summarizer` during indexing. Never produced at query time.
    """

    section_id: str
    gist: str = Field(description="≤ 20 words; the 'scent' in IFT terms")
    synopsis: str = Field(description="one paragraph; ≤ 80 words")
    digest: str = Field(description="multi-paragraph; ≤ 300 words")
    model: str = Field(description="identifier of the LLM that produced these")
    generated_at: datetime


class Mention(_Frozen):
    """A single occurrence of an entity inside a section."""

    section_id: str
    span: Span


class Entity(_Frozen):
    """A canonicalized term/concept and its mentions throughout the document."""

    canonical: str = Field(min_length=1)
    surface_forms: tuple[str, ...]
    kind: EntityKind
    mentions: tuple[Mention, ...]


class XRef(_Frozen):
    """A directed edge in the cross-reference graph."""

    src: str = Field(description="section_id of the source")
    dst: str = Field(description="section_id of the destination")
    kind: XRefKind
    confidence: float = Field(ge=0.0, le=1.0)
    span: Span


class Document(_Frozen):
    """A fully ingested document.

    Produced by Layer 1 (Ingestion). The sole input to Layer 2 (Index).
    """

    id: str = Field(min_length=1, description="human-readable doc_id, slug-based")
    source_path: Path
    source_hash: str = Field(description="sha256 of the source bytes, hex-encoded")
    sections: tuple[SectionNode, ...]
    indexed_at: datetime
    cairn_version: str
